
services:
  db:
    image: mysql:8.0
    container_name: movielog-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: movielog
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: movielog-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: root
      DB_DATABASE: movielog

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: movielog-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend